source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import *


app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('products/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/reviews/add/', ProductReviewCreateView.as_view(), name='product_review_add'),
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg, Sum

CATEGORY_CHOICES = [('food', 'Еда',), ('toys', 'Игрушки'), ('books', 'Книги'), ('clothes', 'Одежда'),
                    ('other', 'Другое')]

RATING_RANGE = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
]


class Product(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Название')
    category = models.CharField(max_length=100, null=False, blank= False, choices=CATEGORY_CHOICES,
                                verbose_name='Категория')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    img = models.ImageField(null=True, blank=True, upload_to='product_pics', verbose_name='Картинка')

    def __str__(self):
        return f'{self.pk}. {self.name}'

    def get_avg_rating(self):
        total = 0
        reviews = Review.objects.filter(product=self.pk)
        if reviews:
            for i in reviews:
                total += int(i.rating)
            return total / len(reviews)
        else:
            return total

    class Meta:
        verbose_name = 'Товар/Услуга'
        verbose_name_plural = 'Товары/Услуги'


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='products',
                               verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', related_name='reviews', on_delete=models.CASCADE,
                                verbose_name='Товар')
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Отзыв')
    rating = models.IntegerField(verbose_name='Оценка', choices=RATING_RANGE)

    def __str__(self):
        return f'{self.author} | {self.product}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms
from .models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']

source/webapp/views/product_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import Product
from webapp.forms import ProductForm


class IndexView(ListView):
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 5
    paginate_orphans = 0

    def get_queryset(self):
        return Product.objects.all().order_by('name')


class ProductView(DetailView):
    template_name = 'product/product.html'
    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        reviews = product.reviews.order_by('author')
        context['reviews'] = reviews
        return context


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'product/create.html'
    form_class = ProductForm
    permission_required = 'webapp.add_product'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'product/update.html'
    form_class = ProductForm
    model = Product
    permission_required = 'webapp.change_product'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'product/delete.html'
    model = Product
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_product')

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Review, Product
from webapp.forms import ProductReviewForm


class ProductReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'review/create.html'
    form_class = ProductReviewForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        review = form.save(commit=False)
        review.product = product
        review.author = self.request.user
        review.save()
        return redirect('webapp:product_view', pk=product.pk)


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/update.html'
    form_class = ProductReviewForm
    permission_required = 'webapp.change_review'

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    permission_required = 'webapp.delete_review'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})

source/webapp/templates/product/create.html
{% extends "partial/../base.html" %}

{% block title %}Create{% endblock %}

{% block content %}
    <h1>Create Product</h1>
        {% url "webapp:product_create"  as action_url %}
        {% include 'partial/form.html' with button_text='Добавить' action_url=action_url form_method='post' %}
{% endblock %}

source/webapp/templates/product/delete.html
{% extends "partial/../base.html" %}

{% block title %}Delete{% endblock %}

{% block menu %}
    <li class="nav-item my-2"><a class="nav-link" href="{% url 'webapp:product_view' product.pk %}">Назад</a></li>
{% endblock %}


{% block content %}
    <h1 class="title mt-5">Вы уверены, что хотите удалить данный товар/услугу: "{{ product }}"?</h1>
    <form method="POST" action="{% url "webapp:product_delete" product.pk %}" class="text-center">
        {% csrf_token %}
        <p><input class="btn btn-primary" type="submit" value="Да"></p>
        <p><a class="btn btn-primary" href="{% url "webapp:product_view" product.pk %}" role="button">Нет</a></p>
    </form>
{% endblock %}

source/webapp/templates/product/index.html
{% extends 'partial/../base.html' %}

{% block title %}Отзовик{% endblock %}

{% block content %}
    <div class="title mt-5 pb-4" style="text-align: center"><h1>Товары и услуги</h1></div>
     {% include 'partial/product_list.html' %}
{% endblock %}

source/webapp/templates/product/product.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}View{% endblock %}

{% block menu %}
    {% if perm.webapp.change_product %}
    <li class="nav-item my-2"><a class="nav-link" href="{% url 'webapp:product_update' product.pk %}">Редактировать</a></li>
    {% endif %}
    {% if perm.webapp.delete_product %}
    <li class="nav-item my-2"><a class="nav-link" href="{% url 'webapp:product_delete' product.pk %}">Удалить</a></li>
    {% endif %}
    <li class="nav-item my-2"><a class="nav-link" href="{% url 'webapp:product_review_add' product.pk %}">Добавить отзыв</a></li>
{% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-header">{{ product.get_category_display }}</div>
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <p class="card-text">Средняя оценка: {{ product.get_avg_rating|default_if_none:0 }}</p>
            {% if product.img%}
                <img class="card-img-left" src="{{ product.img.url }}" width="250" height="250" alt="product picture">
            {% else %}
                <img class="card-img-left" src="{% static 'img/default.png' %}" width="250" height="250" alt="product picture">
            {% endif %}
            <div class="card-footer my-2">
            {% if perms.webapp.change_product %}
            <a href="{% url 'webapp:product_update' product.pk %}" class="card-link">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
            </a>
            {% endif %}
            {% if perms.webapp.delete_product %}
            <a href="{% url 'webapp:product_delete' product.pk %}" class="card-link">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-minus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h5v-1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v2.5A1.5 1.5 0 0 0 10.5 6H13v2h1V6L9 1z"/>
                    <path fill-rule="evenodd" d="M11 11.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/>
                </svg>
            </a>
            {% endif %}
            </div>
        </div>
            <hr/>
    <h3>Отзывы:</h3>
    {% for review in reviews %}
    <div class="card text-center my-2">
        <div class="card-header"><a class="card-link" href="{% url 'accounts:detail' review.author.pk %}">{{ review.author }}({{ review.author.email }})</a></div>
        <div class="card-body">
            <div class="card-text">
                <h4>Оценка: {{ review.rating }}</h4>
                <div class="pre">{{ review.text }}</div>
                {% if perms.webapp.change_review or review.author == request.user %}
                    <a class="card-link mr-5 mb-2" href="{% url 'webapp:review_update' review.pk %}" style="float:right;">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M5.707 13.707a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391L10.086 2.5a2 2 0 0 1 2.828 0l.586.586a2 2 0 0 1 0 2.828l-7.793 7.793zM3 11l7.793-7.793a1 1 0 0 1 1.414 0l.586.586a1 1 0 0 1 0 1.414L5 13l-3 1 1-3z"/>
                            <path fill-rule="evenodd" d="M9.854 2.56a.5.5 0 0 0-.708 0L5.854 5.855a.5.5 0 0 1-.708-.708L8.44 1.854a1.5 1.5 0 0 1 2.122 0l.293.292a.5.5 0 0 1-.707.708l-.293-.293z"/>
                            <path d="M13.293 1.207a1 1 0 0 1 1.414 0l.03.03a1 1 0 0 1 .03 1.383L13.5 4 12 2.5l1.293-1.293z"/>
                        </svg>
                    </a>
                {% endif %}
                {% if perms.webapp.delete_review or review.author == request.user %}
                    <a class="card-link mr-3" href="{% url 'webapp:review_delete' review.pk %}" style="float:right;">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                {% endif %}
                {% empty %}
                <p>Нет отзывов</p>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/product/update.html
{% extends 'base.html' %}

{% block title %}Update{% endblock %}

{% block menu %}
    <li class="nav-item my-2"><a class="nav-link" href="{% url 'webapp:product_view' product.pk %}">Назад</a></li>
{% endblock %}

{% block content %}
    <h1>Update Product</h1>

    {% url 'webapp:product_update' product.pk as action_url %}
    {% include 'partial/form.html' with form_method='post' button_text='Редактировать' action_url=action_url %}
{% endblock %}